# Generated by Django 6.0.2 on 2026-02-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGlobalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('posts_count', models.IntegerField(default=0)),
                ('avg_sentiment', models.FloatField(default=0)),
                ('likes_sum', models.BigIntegerField(default=0)),
                ('retweets_sum', models.BigIntegerField(default=0)),
                ('replies_sum', models.BigIntegerField(default=0)),
                ('quotes_sum', models.BigIntegerField(default=0)),
                ('impressions_sum', models.BigIntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('top_trends', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_global_metrics',
            },
        ),
        migrations.CreateModel(
            name='Rolling7dGlobalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_end_day', models.DateField(unique=True)),
                ('posts_count', models.IntegerField(default=0)),
                ('avg_sentiment', models.FloatField(default=0)),
                ('likes_sum', models.BigIntegerField(default=0)),
                ('retweets_sum', models.BigIntegerField(default=0)),
                ('replies_sum', models.BigIntegerField(default=0)),
                ('quotes_sum', models.BigIntegerField(default=0)),
                ('impressions_sum', models.BigIntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('top_trends', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rolling_7d_global_metrics',
            },
        ),
        migrations.CreateModel(
            name='DailyAffiliationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('affiliation', models.CharField(db_index=True, max_length=32)),
                ('posts_count', models.IntegerField(default=0)),
                ('avg_sentiment', models.FloatField(default=0)),
                ('likes_sum', models.BigIntegerField(default=0)),
                ('retweets_sum', models.BigIntegerField(default=0)),
                ('replies_sum', models.BigIntegerField(default=0)),
                ('quotes_sum', models.BigIntegerField(default=0)),
                ('impressions_sum', models.BigIntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('top_trends', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_affiliation_metrics',
                'indexes': [models.Index(fields=['day', 'affiliation'], name='idx_daily_aff_day_aff')],
                'constraints': [models.UniqueConstraint(fields=('day', 'affiliation'), name='uniq_daily_aff_metric')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_post_id', models.BigIntegerField(unique=True)),
                ('author_id', models.BigIntegerField(db_index=True)),
                ('author_name', models.CharField(max_length=120)),
                ('affiliation', models.CharField(db_index=True, max_length=32)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('day', models.DateField(db_index=True)),
                ('sentiment_score', models.FloatField(db_index=True)),
                ('sentiment_label', models.CharField(choices=[('negative', 'negative'), ('neutral', 'neutral'), ('positive', 'positive')], db_index=True, max_length=16)),
                ('like_count', models.BigIntegerField(default=0)),
                ('retweet_count', models.BigIntegerField(default=0)),
                ('reply_count', models.BigIntegerField(default=0)),
                ('quote_count', models.BigIntegerField(default=0)),
                ('impression_count', models.BigIntegerField(default=0)),
                ('public_metrics', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'posts',
                'indexes': [models.Index(fields=['day', 'affiliation'], name='idx_post_day_aff'), models.Index(fields=['affiliation', 'created_at'], name='idx_post_aff_created'), models.Index(fields=['sentiment_label', 'day'], name='idx_post_sent_day')],
            },
        ),
        migrations.CreateModel(
            name='Rolling7dAffiliationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_end_day', models.DateField(db_index=True)),
                ('affiliation', models.CharField(db_index=True, max_length=32)),
                ('posts_count', models.IntegerField(default=0)),
                ('avg_sentiment', models.FloatField(default=0)),
                ('likes_sum', models.BigIntegerField(default=0)),
                ('retweets_sum', models.BigIntegerField(default=0)),
                ('replies_sum', models.BigIntegerField(default=0)),
                ('quotes_sum', models.BigIntegerField(default=0)),
                ('impressions_sum', models.BigIntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('top_trends', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rolling_7d_affiliation_metrics',
                'indexes': [models.Index(fields=['window_end_day', 'affiliation'], name='idx_roll7_aff_day_aff')],
                'constraints': [models.UniqueConstraint(fields=('window_end_day', 'affiliation'), name='uniq_rolling7_aff_metric')],
            },
        ),
    ]
