# Generated by Django 6.0.2 on 2026-02-23 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('selected_accounts', models.TextField(blank=True)),
                ('x_api_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_dashboards',
                'indexes': [models.Index(fields=['owner', 'updated_at'], name='idx_user_dash_owner_updated')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='uniq_owner_dashboard_name')],
            },
        ),
    ]
