# Generated by Django 6.0.2 on 2026-02-24 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userdashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dashboard.userdashboard'),
        ),
        migrations.AlterField(
            model_name='post',
            name='x_post_id',
            field=models.BigIntegerField(),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['source_dashboard', 'day'], name='idx_post_dash_day'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(condition=models.Q(('source_dashboard__isnull', True)), fields=('x_post_id',), name='uniq_main_post_xid'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(condition=models.Q(('source_dashboard__isnull', False)), fields=('source_dashboard', 'x_post_id'), name='uniq_workspace_post_xid'),
        ),
    ]
