# Generated by Django 6.0.2 on 2026-02-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_post_source_dashboard_alter_post_x_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdashboard',
            name='fetch_posts_per_account',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='fetch_window_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
