# Generated by Django 6.0.2 on 2026-03-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_userdashboard_fetch_posts_per_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="N8NReply",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workspace_key", models.CharField(db_index=True, default="main", max_length=32)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("requested_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "source_dashboard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="n8n_replies",
                        to="dashboard.userdashboard",
                    ),
                ),
            ],
            options={
                "db_table": "n8n_replies",
                "indexes": [
                    models.Index(fields=["workspace_key", "received_at"], name="idx_n8n_reply_ws_received"),
                    models.Index(fields=["workspace_key", "requested_at"], name="idx_n8n_reply_ws_requested"),
                ],
            },
        ),
    ]
